#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -Iinclude
CFLAGS = -std=c++11 -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = -l boost_system -l boost_filesystem -l boost_iostreams -l cryptopp

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/HideMeFatty-v0.3

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O3
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/HideMeFatty-v0.3

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/DirectoryEntry.o $(OBJDIR_DEBUG)/src/DistributedMemoryMapper.o $(OBJDIR_DEBUG)/src/Fat32Manager.o $(OBJDIR_DEBUG)/src/FatStructs.o $(OBJDIR_DEBUG)/src/FileHidder.o $(OBJDIR_DEBUG)/src/MappedFileManager.o $(OBJDIR_DEBUG)/src/main.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/DirectoryEntry.o $(OBJDIR_RELEASE)/src/DistributedMemoryMapper.o $(OBJDIR_RELEASE)/src/Fat32Manager.o $(OBJDIR_RELEASE)/src/FatStructs.o $(OBJDIR_RELEASE)/src/FileHidder.o $(OBJDIR_RELEASE)/src/MappedFileManager.o $(OBJDIR_RELEASE)/src/main.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/DirectoryEntry.o: src/DirectoryEntry.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/DirectoryEntry.cpp -o $(OBJDIR_DEBUG)/src/DirectoryEntry.o

$(OBJDIR_DEBUG)/src/DistributedMemoryMapper.o: src/DistributedMemoryMapper.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/DistributedMemoryMapper.cpp -o $(OBJDIR_DEBUG)/src/DistributedMemoryMapper.o

$(OBJDIR_DEBUG)/src/Fat32Manager.o: src/Fat32Manager.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Fat32Manager.cpp -o $(OBJDIR_DEBUG)/src/Fat32Manager.o

$(OBJDIR_DEBUG)/src/FatStructs.o: src/FatStructs.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/FatStructs.cpp -o $(OBJDIR_DEBUG)/src/FatStructs.o

$(OBJDIR_DEBUG)/src/FileHidder.o: src/FileHidder.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/FileHidder.cpp -o $(OBJDIR_DEBUG)/src/FileHidder.o

$(OBJDIR_DEBUG)/src/MappedFileManager.o: src/MappedFileManager.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/MappedFileManager.cpp -o $(OBJDIR_DEBUG)/src/MappedFileManager.o

$(OBJDIR_DEBUG)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/main.cpp -o $(OBJDIR_DEBUG)/src/main.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/DirectoryEntry.o: src/DirectoryEntry.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/DirectoryEntry.cpp -o $(OBJDIR_RELEASE)/src/DirectoryEntry.o

$(OBJDIR_RELEASE)/src/DistributedMemoryMapper.o: src/DistributedMemoryMapper.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/DistributedMemoryMapper.cpp -o $(OBJDIR_RELEASE)/src/DistributedMemoryMapper.o

$(OBJDIR_RELEASE)/src/Fat32Manager.o: src/Fat32Manager.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Fat32Manager.cpp -o $(OBJDIR_RELEASE)/src/Fat32Manager.o

$(OBJDIR_RELEASE)/src/FatStructs.o: src/FatStructs.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/FatStructs.cpp -o $(OBJDIR_RELEASE)/src/FatStructs.o

$(OBJDIR_RELEASE)/src/FileHidder.o: src/FileHidder.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/FileHidder.cpp -o $(OBJDIR_RELEASE)/src/FileHidder.o

$(OBJDIR_RELEASE)/src/MappedFileManager.o: src/MappedFileManager.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/MappedFileManager.cpp -o $(OBJDIR_RELEASE)/src/MappedFileManager.o

$(OBJDIR_RELEASE)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/main.cpp -o $(OBJDIR_RELEASE)/src/main.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

